### PR TITLE
#185: Fixed missed scenarios for BDD

### LINKED ISSUE #185: Missed failed Scenario Outline test examples in the report
If Scenario Outline has multiple test examples, and any of those test examples fail - the next failed examples will not be reported to the Report Portal launch.
E.g of Scenario Outline:
```
 Scenario Outline: Test scenario with multiple examples
    Given I open the app
    When I do something <action>
    Then I assert that <action> is <assert>

    Examples:
      | action | assert |
      | test   | true   |
      | sleep  | false  |
      | eat    | true   |
      | work   | false  |
      | dammy  | false  |
      | walk   | true   |
```
After the execution, the result will be next:
```
  Examples:
      | action | assert | 
      | test   | true   | - passed, reported to RP
      | sleep  | false  | - failed, reported to RP
      | eat    | true   | - passed, reported to RP
      | work   | false  | - **failed, not be reported to RP**
      | dammy  | false  | - **failed, not be reported to RP**
      | walk   | true   | - passed, reported to RP
```
How it looks in IntelliJ IDEA
image
And how it is reported in RP, examples 4 and  5 were not added to the RP
image
I`m using the latest, 1.6.0, version of serenity-reportportal-integration

### PR DESCRIPTION
**Pull request by grey-rain**
#### Issue
#185 

#### Cause
It seems like call order for listeners of different types has been changed.
Current fix is implemented only for BDD Scenarios (since we've got a request), however, other types of tests also have issues reporting their Failed results. 
Screenshot 2024-08-29 at 22 20 11

Issues in other test types results will be addressed separately.

### CODE REVIEW

File: src/main/java/com/github/invictum/reportportal/ReportPortalListener.java [hunk 1]
```diff
@@ -129,7 +130,10 @@ public void stepFinished(List<ScreenshotAndHtmlSource> list, ZonedDateTime zoned
 
     @Override
     public void testFailed(TestOutcome testOutcome, Throwable throwable) {
-        // Not used by listener
+        TestType testType = TestType.byTestSource(testOutcome.getTestSource());
+        if (testType == TestType.BDD) {
+            testFinished(testOutcome);
+        }
```
Comment (Invictum) [inline src/main/java/com/github/invictum/reportportal/ReportPortalListener.java:134]: 1. This might be dangerous without extensive testing of all supported bdd style tests.
2. Might worths to add a unit test for this logic.

**Review by Invictum — DISMISSED** [review]

**Review by Invictum — APPROVED** [review]
